### ISSUE TITLE
Add WHMCS 8 compatibility

### ISSUE THREAD

**Issue by khalequzzaman17** [websavers/WHMCS-mailcow#2]
Dear sir,

Please update the WHMCS module. It's been a long time the module is using old API of mailcow. So, it needs to be updated. Please update the module so that it works on WHMCS v7.x.x and v8.x.x.

Thanks!

**Comment by jas8522** [comment]
I'm afraid we no longer use this module, and my time is severely limited until the end of this year. I'll gladly accept pull requests if you'd like to contribute code.

**Comment by rorry47** [comment]
Hello. I slightly updated your module for the new API and abandoned the Curl library, replacing it with an internal one.
https://github.com/rorry47/mailcow_module_WHMCS

**Comment by jas8522** [comment]
@rorry47 Great! Thanks for letting everyone know it's over there :)
